version: "3.8"
services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: eleza
    volumes:
      - db_data:/var/lib/mysql

  eleza:
    build: .
    container_name: app
    command: python -m flask run -h 0.0.0.0 -p 5005
    volumes:
      - .:/usr/src/app
    ports:
      - 5005:5005
    depends_on:
      - db

volumes:
  db_data: